ShoesStore/ShoesStore/Models/Shoe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ShoesStore.Models
{
    public class Shoe
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Shoe's name must not be emptied!!!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Price must not be emptied!!!")]
        [Range(0, Double.MaxValue)]
        public double Price { get; set; }
        [Required(ErrorMessage = "Quantity must not be emptied!!!")]
        [Range(0, Int32.MaxValue)]
        public int Quantity { get; set; }
        public string ShortDes { get; set; }
        public string Image { get; set; }
        [Required(ErrorMessage = "Shoe status must not be emptied!!!")]
        [DisplayName("Shoe Status")]
        public bool ShoeLive { get; set; }
        [Required]
        public int PublisherId { get; set; }
        [Required]
        public int CategoryId { get; set; }

        public Publisher Publisher { get; set; }
        public Category Category { get; set; }
    }
}

ShoesStore/ShoesStore/Controllers/ShoeController.cs
#nullable enable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using PagedList;
using PagedList.Core.Mvc;
using ShoesStore.Data;
using ShoesStore.Models;
using X.PagedList;

namespace ShoesStore.Controllers
{

    [Route("shoe")]
    public class ShoeController : Controller
    {
        private readonly int _pageSize = 6;
        private readonly ApplicationDbContext _db;

        public ShoeController(ApplicationDbContext db)
        {
            _db = db;
        }
        [Route("")]
        [Route("allshoe")]
        public IActionResult AllShoe(int? page)
        {
            var shoes = _db.Shoes.OrderByDescending(p => p.Id).ToPagedList(page ?? 1, _pageSize);
            ViewBag.allShoe = "AllShoe";
            ViewBag.pageSize = _pageSize;
            return View(shoes);
        }

        [Route("detail/{id}")]
        public IActionResult Detail(int id)
        {
            var shoe = _db.Shoes.SingleOrDefault(p => p.Id == id);

            if (shoe != null)
            {
                Debug.WriteLine(shoe.PublisherId);

                shoe.Publisher = _db.Publishers.SingleOrDefault(p => p.Id == shoe.PublisherId);
                shoe.Category = _db.Categories.SingleOrDefault(p => p.Id == shoe.CategoryId);
            }
            return View(shoe);
        }

        [Route("find/{keyword?}")]
        public IActionResult Find(string? keyword, int? page)
        {
            if (keyword == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (keyword.Length == 0)
                {
                    var shoes = _db.Shoes.OrderByDescending(p => p.Id).ToPagedList(page ?? 1, _pageSize);
                    @ViewBag.find = "Find";
                    @ViewBag.keyword = keyword;
                    return View("AllShoe", shoes);
                }
                else
                {
                    var shoes = _db.Shoes.Where(p => p.Name.Contains(keyword)).OrderByDescending(p => p.Id).ToPagedList(page ?? 1, _pageSize);
                    @ViewBag.find = "Find";
                    @ViewBag.keyword = keyword;
                    return View("AllShoe", shoes);
                }
            }
        }
    }
}

ShoesStore/ShoesStore/Views/Shoe/AllShoe.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<ShoesStore.Models.Shoe>
@{
    ViewData["Title"] = "All shoes";
}

<!-- New Arrivals section start -->
<div class="collection_text">Shoes</div>
<div class="collection_section layout_padding">
    <div class="container">
        @if (@Model.Count != 0)
        {
            <h1 class="new_text"><strong>New Arrivals Products</strong></h1>
            <p class="consectetur_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
        }
        else
        {

            <h1 class="new_text" style="text-align: center; padding-bottom: 40px"><strong>No shoes is suitable!!</strong></h1>
        }
    </div>
</div>
<div class="layout_padding gallery_section">
    <div class="container">
        <div class="row">
            @foreach (var shoe in Model)
            {
                <div class="col-sm-4">
                    <div class="best_shoes">
                        <p class="best_text">@shoe.Name</p>
                        <div class="shoes_icon"><a asp-controller="Shoe" asp-action="Detail" asp-route-id="@shoe.Id"><img src="~/images/@shoe.Image"></a></div>
                        <div class="star_text">
                            <div class="left_part">
                                <ul>
                                    <li><a href="#"><img src="~/images/star-icon.png"></a></li>
                                    <li><a href="#"><img src="~/images/star-icon.png"></a></li>
                                    <li><a href="#"><img src="~/images/star-icon.png"></a></li>
                                    <li><a href="#"><img src="~/images/star-icon.png"></a></li>
                                    <li><a href="#"><img src="~/images/star-icon.png"></a></li>
                                </ul>
                            </div>
                            <div class="right_part">
                                <div class="shoes_price">$ <span style="color: #ff4e5b;">@shoe.Price</span></div>
                            </div>
                            <div class="buy_now_bt" style="width: 400px; padding-right: 50px">
                                <a class="buy_text" style="padding: 8px" asp-area="User" asp-controller="Cart" asp-action="AddToCart" asp-route-id="@shoe.Id">Buy Now</a>
                            </div>
                        </div>
                    </div>
                </div>

            }

        </div>
        @if (Model.Count != 0 && Model.Count > ViewBag.pageSize)
        {
            <div id="container" style="margin-left: 20px">
                <p></p>
                <p></p>
                <div class="pagination" style="margin-left: 400px">
                    @if (@ViewBag.allShoe == null)
                    {
                        @Html.PagedListPager(Model, page => Url.Action("Find", new { page, keyword = @ViewBag.keyword }))
                    }
                    else
                    {
                        @Html.PagedListPager(Model, page => Url.Action("AllShoe", new { page }))
                    }
                </div>
            </div>
        }
    </div>
</div>

ShoesStore/ShoesStore/Views/Shoe/Detail.cshtml
@model Shoe
@{
    ViewData["Title"] = "Detail";
}

<div class="collection_text">@Model.Name</div>
<div class="about_main layout_padding">
    <div class="collection_section">
        <div class="container">
            <h1 class="new_text"><strong>@Model.Name</strong></h1>
            <p class="consectetur_text">@Model.ShortDes</p>
        </div>
    </div>
    <div class="collectipn_section_3 layout_padding">
        <div class="container">
            <div class="racing_shoes">
                <div class="row">
                    <div class="col-md-8">
                        <div class="shoes-img3"><img src="~/images/@Model.Image"></div>
                    </div>
                    <div class="col-md-4">
                        <div class="sale_text"><strong>Sale <br><span style="color: #0a0506;">JOGING</span> <br>SHOES</strong></div>
                        <div class="number_text"><strong>$ <span style="color: #0a0506">@Model.Price</span></strong></div>
                        <button class="seemore"><a asp-controller="Shoe" asp-action="AllShoe">See More</a></button>
                    </div>
                </div>
            </div>
            <strong>Publisher: </strong> @Model.Publisher.Name<br />
            <strong>Category: </strong> @Model.Category.Name <br />
            <strong>Quantity: </strong> @Model.Quantity <br />
            <strong>Status: </strong> @(Model.ShoeLive == true ? "In Stock" : "Out Of Stock")<br />
        </div>
        
    </div>
   

</div>